# Generated by Django 3.1.7 on 2021-03-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210307_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_create_update_delete_authors', 'update/edit/delete authors via web'),)},
        ),
    ]
